# @name get-prompts
GET http://localhost:5000/prompts

###

# @name create-transcription
POST http://localhost:5000/videos/6befb88f-7ebf-437f-842e-04f3d46466fc/transcription
Content-Type: application/json

{
    "prompt" : "clean architecture, ddd, splash"
}
